### ISSUE TITLE
Purchased Renewable Energy is not settled for a year

### ISSUE THREAD

**Issue by adrianco** [Green-Software-Foundation/real-time-cloud#8]
Purchased renewable energy is reported by GCP and AWS for previous years. AWS provided its 2022 data in July 2023 to report regions where it has 100% purchased energy here https://sustainability.aboutamazon.com/products-services/the-cloud?energyType=true, and GCP provides data for 2021 here https://cloud.google.com/sustainability/region-carbon.

We would like to have an estimate in real time, however the way energy is purchased is a mixture of grid, power purchase agreements, and renewable energy credits. RECs can be traded for up to a year, so after a year (say 2022) is over and data is finalized, RECs can be purchased for 2022 to get to whatever target percentage is desired, before the numbers are reported.

AWS is currently attributing energy on a per region annual basis using the market method, and lists 100% regions for 2022, and doesn't provide data for other regions. GCP is doing 24/7 calculations using the location method, and reports the percentage of energy that they generated from PPAs for all regions in 2021.

Since this data is not settled in real time, we need to develop a mechanism that indicates the likely bounds of the metric, and report market and location data as separate metrics. For example, in regions where AWS is already claiming 100% renewable for 2022, they could report 100% for 2023 in real time, assuming that they will not backslide on their commitment. For regions that have not yet reached 100%, a 95% confidence interval with mode (most likely) could be provided.

**Comment by adrianco** [comment]
If a PRE% value is provided that doesn't change in real time, this could be combined with closer to real time grid mix estimates to provide a useful metric. For regions that are at 100% renewable like Montreal, there's no variation to exploit for optimization. For regions that are high carbon and low purchased renewable like Singapore, there may be opportunities to optimize in real time.

**Comment by mrchrisadams** [comment]
What woudl the unit here be?

1. carbon intensity as in CO2e / KWh? or
2. the percentage of power with 'coverage' by REC/EACs (i.e. 100% of 100GWh load has corresponding RECs/EACs supply to match this)?

I'm asking in the context of residual carbon intensity being quite different in some countries once purchases and trading of EACs has been accounted for.

I'll refer to two extreme examples from data published in 2020:

- Norway's figures of around 8g of co2 per KWh when you look at avg emissions jumps to 402 Co2 per  KWh once you account for the EACs being traded out of the country
- Iceland jumps from 0g to 402g for the same

Other countries are less dramatic, but you can still see measurable swings - so if you combined regular production + market based figures in a stat, you may miss out on this information, and it would incentivise different actions.

**Comment by adrianco** [comment]
The Iceland and Norway examples highlight the problem this project is trying to address. If a cloud provider in Iceland purchases RECs (as they should) to make sure they have all the benefit of being in Iceland, then they currently have no way to disclose that via a metric that is in the same schema/format as all the other cloud providers and regions.

**Comment by mrchrisadams** [comment]
I've looked into this some more. This settlement issue is something that I think Energy Tag spec tries to address, and there are now projects like https://energytrackandtrace.com run by grid operators to make it possible to query for the status of certificates at a higher frequency than annually.

I know last year there was some work to figure out a spec for an API to allow querying for certificates for a given facility and time period.

The screenshot below is from the API documentation for the Energy Tag spec below, that Future Energy Associates worked on : 

![Screenshot 2023-10-13 at 14 16 26](https://github.com/Green-Software-Foundation/real-time-cloud/assets/17906/9c0a5882-2715-4cd5-9019-f005710aa591)

It shows an API call to fetch a series of certificate URLS for hourly certificates for a given resource and time frame.

Assuming there was an issuer of hourly certificates that supported this same API, then I think it's _technically_ possible at least to demonstrate that a given number of hours of use at a given facility are backed by a matching number of certificates for the generation, and from clean / fossil free sources.

The link below should show an example of a query endnpoint for a 'bundle' of hourly certificates issued, that can be scoped to a specific facility (for location), as well specific time range. So, if you knew when and where you had run a compute job, or made a service available, it would be possible to query for the same hourly certs: 

http://13.41.208.178:8080/#tag/Certificates/operation/query_certificate_bundles_certificates_certificates_query_get

(BTW - apologies about the messy url - I checked with Energy Tag about sharing this link in a public forum like this, and they were happy do to so, but I might update with a an HTTPS link for a named domain later)

I'm not sure of the status of the API in Q4 2023, and I share the link above with the caveat that I think it's in use as a conversation tool, rather than being backed by a live issuer of granular certificates at present.

There are now a number of companies building products to verify that matching certificates exist for a given amount. One example is Granular, who work with Good Energy in the UK, so any IT infrastructure using power from Good Energy would be able to demonstrate ~ 90% hourly matched certificates, using the market based approach.

> Aiming for full data transparency, its Granular Energy platform aims to show business clients how their usage coordinates – on an half-hourly basis – with the power they buy from the company’s renewable generators.
> 
> The new service will provide customers with 24/7 ‘carbon free energy’ data, paving the way for new levels of transparency in carbon reporting and enabling businesses to shift when they use energy to reduce their emissions.
> 
> This will be the first time a UK energy supplier has launched such a service for all of its business customers and Good Energy is offering it as standard at no extra cost.
> 
> The company is working with [software providers Granular Energy](https://www.granular-energy.com/) to match its business customers’ usage with the output of nearly 400 renewable generators across the UK. Good Energy plans to extend the scheme’s coverage over the next year to its full community of 2,000 generators.

[Source - the Energyst](https://theenergyst.com/good-energy-debuts-hourly-based-matching-for-business-customers)

This would definitely be higher resolution than settling once per year, but I'm not sure about what the lag would be yet.

My guess based on earlier convos would be the order of days or hours rather than one a year though.

**Comment by adrianco** [comment]
This discussion in https://github.com/Green-Software-Foundation/real-time-cloud/issues/14 overlaps with this issue. Past data is available for the three main cloud providers in various formats. To provide current data estimates need to be made that provide a range of likely values that will resolve to a final number about half way through the following calendar year. The thought here is that rather than have everyone use last year's data or make their own guesses, this group can collectively make a best estimate of the range and most likely value which can be used for real time calculations.

**Comment by seanmcilroy29** [comment]
Added to #14
